### ISSUE TITLE
HTML script tag expansion in Sublime Text 3

### ISSUE THREAD

**Issue by elbasankadrija** [sergeche/emmet-sublime#596]
After a quick research, it seems to be a long known issue with emmet:

https://github.com/emmetio/emmet/issues/320

Some user mentioned that it's fixed with emmets latest version, but It's still not working for me on sublime text 3. 

You can reproduce it with `script:src` which outputs ==> `script:<script type="text/javascript"></script>` instead of `<script src="js/xyz.js"></script>`

I'm using Sublime Text 3 - Build 3103 with the latest version of emmet-sublime

**Comment by sergeche** [comment]
Make sure there’s no autocomplete popup visible when you hit Tab and document syntax is set to HTML. Everything works fine

**Comment by elbasankadrija** [comment]
That doesn't work
![t8yho7r](https://cloud.githubusercontent.com/assets/12799363/13235005/ec653222-d9bb-11e5-96da-fedc86490b43.gif)


And my syntax is set on HTML

**Comment by mugukamil** [comment]
emmet doesn't working now... after updating...

**Comment by iulo** [comment]
+1  sublime 3103

**Comment by sergeche** [comment]
@elbasankadrija it means there’s `src` snippet expanded by other package. Try to run `sublime.log_commands(True)` command in ST console and check command name when you press Tab

@mugukamil check ST console for errors and try to restart ST

**Comment by elbasankadrija** [comment]
I have no Idea why, but I think it fixed itself overnight? Did you guys push a update?

**Comment by iulo** [comment]
fixed by reinstall emmet

**Comment by blakewatson** [comment]
Emmet would not expand at all. Reinstall fixed it.

**Comment by TehShrike** [comment]
So weird.  I had the same issue, and running "Upgrade/overwrite all packages" didn't fix it.  I uninstalled Emmet, restarted Sublime text, re-installed Emmet, and everything started working dandily.
